### PR TITLE
add regex for email validation

### PR DESCRIPTION
**Pull request by pbellerive**
First contribution, as in the procedure start by P4. 

Email validation mainly based on rfc1035 and 2822

 Thanks

### CODE REVIEW

**Comment by pbellerive** [comment]
issue https://issues.adblockplus.org/ticket/1117

**Comment by palant** [comment]
As noted in the issue, we shouldn't overthink this. A simple `type="email"` on that text field will do just fine.

**Comment by pbellerive** [comment]
Can you give me one to work on?

On Mon, Apr 13, 2015 at 3:22 PM, Wladimir Palant <notifications@github.com>
wrote:

> Closed #11 <https://github.com/adblockplus/adblockplus/pull/11>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adblockplus/adblockplus/pull/11#event-280088821>.
>



-- 
Patrick Bellerive

**Comment by palant** [comment]
Well, I still wouldn't mind a tested patch for this issue.

**Comment by pbellerive** [comment]
do you have an other issue i can work on?

On Tue, Apr 14, 2015 at 3:15 PM, Wladimir Palant <notifications@github.com>
wrote:

> Well, I still wouldn't mind a tested patch for this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adblockplus/adblockplus/pull/11#issuecomment-93024742>
> .
>



-- 
Patrick Bellerive

**Comment by palant** [comment]
I guess you are looking for https://issues.adblockplus.org/query?status=!closed&keywords=~goodfirstbug.

**Pull request closed without merging**
